### ISSUE TITLE
Anaconda installation tutorial not working anymore

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/blog#54]
The post about getting started should be updated as the current installation instructions are not working well anymore.

--> **Put a reference in the old post to the updated version**

**Comment by haesleinhuepf** [comment]
Just more background: We found some issues and workarounds documented here:
https://github.com/BiAPoL/Image-data-science-with-Python-and-Napari-EPFL2022/tree/main/docs/day0#troubleshooting-dll-load-failed

**Comment by haesleinhuepf** [comment]
this was done in #58
