### ISSUE TITLE
devbio-napari installation instructions are outdated

### ISSUE THREAD

**Issue by thawn** [BiAPoL/blog#71]
currently, we have these installation instructions for napari: `mamba create -n my_first_env devbio-napari python=3.9 -c conda-forge`

however, these instructions [can create problems with pyqt](https://github.com/haesleinhuepf/devbio-napari/pull/44).

we should use the current installation instructions from the devbio-napari documentation:

`mamba create --name devbio-napari-env python=3.9 devbio-napari pyqt -c conda-forge -c pytorch`

**Comment by jo-mueller** [comment]
I just stumbled over this error and see that it has already been fixed :) Will close this.
