### ISSUE TITLE
Update mamba blog post to recommend miniforge instead of mambaforge

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/blog#73]
`mambaforge` is discontinued and it is integrated into `miniforge` now (check message below from miniforge Github repository):

<details>
  <summary>Click to see message</summary>
Mambaforge (Discouraged as of September 2023)
With the [release](https://github.com/conda-forge/miniforge/releases/tag/23.3.1-0) of Miniforge3-23.3.1-0, that incorporated the changes in https://github.com/conda-forge/miniforge/pull/277, the packages and configuration of Mambaforge and Miniforge3 are now identical. The only difference between the two is the name of the installer and, subsequently, the default installation directory.

Given its wide usage, there are no plans to deprecate Mambaforge. If at some point we decide to deprecate Mambaforge, it will be appropriately announced and communicated with sufficient time in advance.

As of September 2023, the new usage of Mambaforge is thus discouraged. Bug reports specific to Mambaforge will be closed as won't fix.

</details>

The link should still be this one: https://github.com/conda-forge/miniforge#miniforge3

But we should point to download and install `miniforge` instead of `mambaforge`. The rest can remain the same, `mamba` should work from `miniforge`.

**Comment by zoccoler** [comment]
One of the screenshots needs t be updated

**Comment by stefanhahmann** [comment]
Solved via #80 and #74
